version = 0.1
[default.deploy.parameters]
stack_name = "muse-machine-app"
resolve_s3 = true
s3_prefix = "muse-machine-app"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
